### ISSUE TITLE
Can't build: missing files?

### ISSUE THREAD

**Issue by vasiliev-vb** [lood339/btrf#1]
Hello!

Thanks for sharing project. I'm trying to build it (and add cmake project, as suggested in readme). However, I fail to do it: it seems that file "btrf_param.hpp" (which is mentioned in "btrf_util.hpp" ) is missing. It seems that SCRFRandomSample, mentioned in several other places, should be defined in this file.

**Comment by lood339** [comment]
btrf_param.hpp and btrf_param.cpp are added.

**Comment by vasiliev-vb** [comment]
Thanks for fast reply! 
I got btrf_pose_estimation built, but still have troubles with btrf_test and btrf_train. It seems that src/Walsh_Hadamard directory (mentioned in README) is missing.

**Comment by lood339** [comment]
src/opencv_util/cvx_wht.cpp is added. For the Walsh_Hadamard directory, you may use the code from http://www.faculty.idc.ac.il/toky/Software/wh/code.htm. This project also has a copy of modified Walsh_Hadamard.

**Comment by vasiliev-vb** [comment]
That fixed issue, thanks. I created PR with CMake support.
